# Generated by Django 4.0.1 on 2022-02-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_field',
        ),
    ]
