# Generated by Django 4.0.2 on 2022-02-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_first_name_customer_given_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='feature_product',
            new_name='featured_product',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='given_field',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='place_at',
            new_name='placed_at',
        ),
    ]
